### ISSUE TITLE
Compile error: try-catch inside subscript code fragment

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/examples#3]
```
scoresOf(user: String) = {* val pstmt = conn.prepareStatement(scoresOfStmt)
                                pstmt.setString(1, user)
                            var result: List[Score] = Nil
                            try     {val resultSet = pstmt.executeQuery()
                                     def dbl(name: String) = resultSet.getDouble(name)
                                     while(resultSet.next()) result ::= ((dbl(Col.RIGHT_EYE),
                                                                          dbl(Col. LEFT_EYE), resultSet.getTimestamp(Col.DATE)))}
                            catch   {case t:Throwable => t.printStackTrace()}
                            finally {pstmt.close()}
                            result
                         *}
```

Yields:

> [error] <macro>:1: missing parameter type for expanded function
> [error] The argument types of an anonymous function must be fully known. (SLS 8.5)
> [error] Expected type was: ?
> [error] {case t:Throwable => subscript.DSL._maybeVarCall("t.printStackTrace()")}
> [error] ^
> [error] one error found

**Comment by anatoliykmetyuk** [comment]
Closed from [this](https://github.com/scala-subscript/eye-test/commit/480da04b4e4a8fe0cf1707d8d47c204b3894c0c6).

Due to the fact that everything in code fragments end up in various macros in small pieces, `catch {case t:Throwable => t.printStackTrace()}` becomes `catch subscript.DSL._maybeVarCall("{case t:Throwable => subscript.DSL._maybeVarCall(\"t.printStackTrace()\")}")` and hence is processed as a separate `PartialFunction`, outside `try`'s context. Hence we need to specify its type explicitly, so that it rewrites to `catch   subscript.DSL._maybeVarCall("{case t:Throwable => subscript.DSL._maybeVarCall(\"t.printStackTrace()\")}"): PartialFunction[Throwable, Unit]`.

However, exception handling is supposed to happen from scripts via the dataflow: `a ~/~(e: Throwable)~~> e.printStachTrace()`.

**Comment by AndreVanDelft** [comment]
I think that for the long term this needs a better fix. Would that be possible?
All normal Scala code should be acceptable inside code fragments, except when it clashes with SubScript syntax.

**Comment by anatoliykmetyuk** [comment]
> I think that for the long term this needs a better fix. Would that be possible?

Not until we move the preprocessor back to the compiler, I afraid. So far, macros wrap statements non-selectively, they don't have the context information and can't see they operate in try-catch. This is not the most elegant solution, of course, but I couldn't think of anything better using only macros and the parser.

If you want to leave this issue opened, then I think it'd be better to create it in the main repository. It doesn't belong to the examples.
